# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1bf8bf609dd3e8aa737773a0eb8d7044"
application_url = "https://ruled-lambda-thompson-dl.trycloudflare.com"
embedded = true
name = "product-management-app"
handle = "product-management-app-7"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ruled-lambda-thompson-dl.trycloudflare.com/auth/callback",
  "https://ruled-lambda-thompson-dl.trycloudflare.com/auth/shopify/callback",
  "https://ruled-lambda-thompson-dl.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
